# 00_check_nodes_ready.yml
---
- name: 🔍 Verificar que todos los nodos están listos para instalar K3s
  hosts: all
  gather_facts: false
  become: false

  tasks:

    - name: 🧪 Verificar conectividad SSH (puerto 22)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 5
      delegate_to: localhost

    - name: 🛣️ Verificar ruta por defecto (gateway)
      raw: ip route show default || true
      register: default_route_check
      changed_when: false

    - name: 🌐 Probar resolución DNS de github.com
      raw: getent hosts github.com || true
      register: dns_check
      changed_when: false

    - name: 🔗 Probar conexión HTTPS a https://objects.githubusercontent.com
      raw: curl -s --max-time 5 https://objects.githubusercontent.com/ || true
      register: https_check
      changed_when: false

    - name: 🔧 Evaluar si el nodo está listo
      set_fact:
        node_ready: >-
          {{ (
            ('default' in default_route_check.stdout | default('')) and
            ('github.com' in dns_check.stdout | default('')) and
            (https_check.stdout | length > 0)
          ) | bool }}

    - name: 📊 Reporte del estado del nodo
      debug:
        msg: |
          🚀 Nodo: {{ inventory_hostname }}
          SSH accesible: ✅
          Ruta por defecto: {{ '✅' if 'default' in default_route_check.stdout | default('') else '❌' }}
          DNS resuelve github.com: {{ '✅' if 'github.com' in dns_check.stdout | default('') else '❌' }}
          HTTPS https://objects.githubusercontent.com: {{ '✅' if https_check.stdout | length > 0 else '❌' }}

    - name: 🟢 Nodo listo para instalar K3s
      debug:
        msg: "🟢 Nodo {{ inventory_hostname }} está listo para instalar K3s ✅"
      when: node_ready

    - name: ⚠️ Advertencia si el nodo NO está completamente listo
      debug:
        msg: "⚠️ Nodo {{ inventory_hostname }} NO está completamente listo. Verifica red, DNS o salida HTTPS."
      when: not node_ready