- name: Configurar kubeconfig en nodos trabajadores
  hosts: workers
  become: true
  tasks:
    - name: Crear directorio .kube en el directorio del usuario core
      ansible.builtin.file:
        path: /home/core/.kube
        state: directory
        owner: core
        group: core
        mode: 0755

    - name: Copiar kubeconfig desde el nodo maestro
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/core/.kube/config
        owner: core
        group: core
        mode: 0644
      delegate_to: 10.17.4.21  # Nodo maestro principal
      run_once: true

    - name: Ajustar kubeconfig para que apunte al servidor maestro
      ansible.builtin.shell: |
        sed -i 's/127.0.0.1/10.17.4.21/g' /home/core/.kube/config
      args:
        executable: /bin/bash

    - name: Verificar permisos en el archivo kubeconfig
      ansible.builtin.shell: |
        chown core:core /home/core/.kube/config && chmod 644 /home/core/.kube/config
      args:
        executable: /bin/bash
