# install_k3s.yaml
- name: Instalar y Configurar K3s con alta disponibilidad (etcd) en el Clúster
  hosts: all
  become: true
  gather_facts: no

  vars:
    k3s_url_binary: "https://github.com/k3s-io/k3s/releases/latest/download/k3s"
    k3s_token_path: "/var/lib/rancher/k3s/server/node-token"
    vip_ip: "10.17.5.10"
    k3s_master_ip: "10.17.4.21"

  tasks:
    - name: Asegurar directorios necesarios
      ansible.builtin.raw: |
        mkdir -p /opt/bin /etc/rancher/k3s /var/lib/rancher/k3s/server
      when: inventory_hostname in groups['masters'] + groups['longhorn_nodes']

    - name: Descargar e instalar K3s binario
      ansible.builtin.raw: |
        curl -Lo /opt/bin/k3s "{{ k3s_url_binary }}" && chmod +x /opt/bin/k3s
      args:
        timeout: 600
      when: inventory_hostname in groups['masters'] + groups['longhorn_nodes']

    - name: Verificar que el binario no está en uso (Solo para el primer master)
      ansible.builtin.raw: fuser -k /opt/bin/k3s || true
      when: inventory_hostname == k3s_master_ip

    - name: Crear enlaces simbólicos
      ansible.builtin.raw: |
        ln -sf /opt/bin/k3s /opt/bin/kubectl
        ln -sf /opt/bin/k3s /opt/bin/crictl
        ln -sf /opt/bin/k3s /opt/bin/ctr
      when: inventory_hostname in groups['masters'] + groups['longhorn_nodes']

    - name: Configurar primer nodo master
      ansible.builtin.raw: |
        cat <<EOF > /etc/systemd/system/k3s.service
        [Unit]
        Description=Lightweight Kubernetes
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=notify
        ExecStartPre=-/sbin/modprobe br_netfilter
        ExecStartPre=-/sbin/modprobe overlay
        ExecStart=/opt/bin/k3s server --cluster-init --tls-san {{ vip_ip }} --node-ip {{ ansible_host }} --advertise-address {{ ansible_host }} --write-kubeconfig /etc/rancher/k3s/k3s.yaml --write-kubeconfig-mode 644
        Restart=always
        KillMode=process
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity

        [Install]
        WantedBy=multi-user.target
        EOF
      when: inventory_hostname == k3s_master_ip

    - name: Iniciar primer nodo master
      ansible.builtin.raw: |
        systemctl daemon-reload
        systemctl enable k3s
        systemctl start k3s
      register: k3s_start_result
      when: inventory_hostname == k3s_master_ip

    - name: Esperar a que K3s esté activo en el primer master
      ansible.builtin.raw: |
        timeout=120
        while ! systemctl is-active k3s >/dev/null 2>&1 && [ $timeout -gt 0 ]; do
          echo "Esperando a que K3s esté activo... ($timeout s restantes)"
          sleep 5
          timeout=$((timeout-5))
        done
        [ $timeout -le 0 ] && echo "Timeout: K3s no está activo" && exit 1 || true
      when: inventory_hostname == k3s_master_ip

    - name: Esperar que el token del master esté disponible
      ansible.builtin.raw: |
        timeout=120
        while [ ! -f "{{ k3s_token_path }}" ] && [ $timeout -gt 0 ]; do
          echo "Esperando el archivo node-token... ($timeout s restantes)"
          sleep 5
          timeout=$((timeout-5))
        done
        [ $timeout -le 0 ] && echo "Timeout al esperar el token" && exit 1 || true
      delegate_to: "{{ k3s_master_ip }}"
      run_once: true

    - name: Obtener token del master (compatibilidad Flatcar)
      ansible.builtin.raw: cat "{{ k3s_token_path }}"
      register: k3s_token_output
      delegate_to: "{{ k3s_master_ip }}"
      run_once: true
      changed_when: false

    - name: Depurar el token obtenido (para verificacion)
      debug:
        msg: "K3s Token: {{ k3s_token_output.stdout | trim }}"
      run_once: true