# install_k3s.yaml
- name: Instalar y Configurar K3s con alta disponibilidad (etcd) en el Clúster
  hosts: all
  become: true
  gather_facts: no

  vars:
    k3s_version: "v1.33.1+k3s1"
    k3s_url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    k3s_token_path: "/var/lib/rancher/k3s/server/node-token"
    vip_ip: "192.168.0.32"
    k3s_master_ip: "10.17.4.21"

  tasks:
    - name: Asegurar directorios necesarios
      ansible.builtin.raw: |
        mkdir -p /opt/bin /etc/rancher/k3s /var/lib/rancher/k3s/server
      when: inventory_hostname in groups['masters'] + groups['longhorn_nodes']

    - name: Descargar e instalar K3s
      ansible.builtin.raw: |
        curl -Lo /opt/bin/k3s "{{ k3s_url }}" && chmod +x /opt/bin/k3s
      args:
        timeout: 600
      when: inventory_hostname in groups['masters'] + groups['longhorn_nodes']

    - name: Eliminar binario en uso (si aplica)
      ansible.builtin.raw: fuser -k /opt/bin/k3s || true
      when: inventory_hostname == k3s_master_ip

    - name: Crear enlaces simbólicos
      ansible.builtin.raw: |
        ln -sf /opt/bin/k3s /opt/bin/kubectl
        ln -sf /opt/bin/k3s /opt/bin/crictl
        ln -sf /opt/bin/k3s /opt/bin/ctr
      when: inventory_hostname in groups['masters'] + groups['longhorn_nodes']

    - name: Configurar primer nodo master
      ansible.builtin.raw: |
        cat <<EOF > /etc/systemd/system/k3s.service
        [Unit]
        Description=Lightweight Kubernetes
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=notify
        ExecStartPre=-/sbin/modprobe br_netfilter
        ExecStartPre=-/sbin/modprobe overlay
        ExecStart=/opt/bin/k3s server \
          --cluster-init \
          --tls-san {{ vip_ip }} \
          --node-ip {{ ansible_host }} \
          --advertise-address {{ ansible_host }} \
          --write-kubeconfig /etc/rancher/k3s/k3s.yaml \
          --write-kubeconfig-mode 644
        Restart=always
        KillMode=process
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity

        [Install]
        WantedBy=multi-user.target
        EOF
      when: inventory_hostname == k3s_master_ip

    - name: Iniciar primer nodo master
      ansible.builtin.raw: |
        systemctl daemon-reload
        systemctl enable k3s
        systemctl start k3s
      when: inventory_hostname == k3s_master_ip

    - name: Esperar a que K3s esté activo en el primer master
      ansible.builtin.raw: |
        timeout=120
        while ! systemctl is-active k3s >/dev/null 2>&1 && [ $timeout -gt 0 ]; do
          echo "Esperando a que K3s esté activo... ($timeout s restantes)"
          sleep 5
          timeout=$((timeout-5))
        done
        [ $timeout -le 0 ] && echo "Timeout: K3s no está activo" && exit 1 || true
      when: inventory_hostname == k3s_master_ip

    - name: Esperar que la API K3s esté disponible a través de la VIP
      wait_for:
        host: "{{ vip_ip }}"
        port: 6443
        timeout: 300
        state: started
        delay: 10
      delegate_to: localhost
      run_once: true
      when: inventory_hostname == k3s_master_ip

    - name: Esperar que el token del master esté disponible
      ansible.builtin.raw: |
        timeout=120
        while [ ! -f "{{ k3s_token_path }}" ] && [ $timeout -gt 0 ]; do
          echo "Esperando el archivo node-token... ($timeout s restantes)"
          sleep 5
          timeout=$((timeout-5))
        done
        [ $timeout -le 0 ] && echo "Timeout al esperar el token" && exit 1 || true
      delegate_to: "{{ k3s_master_ip }}"
      run_once: true

    - name: Obtener token del master (compatibilidad Flatcar)
      ansible.builtin.raw: cat "{{ k3s_token_path }}"
      register: k3s_token_output
      delegate_to: "{{ k3s_master_ip }}"
      run_once: true
      changed_when: false

    - name: Depurar el token obtenido (para verificacion)
      debug:
        msg: "K3s Token: {{ k3s_token_output.stdout | trim }}"
      run_once: true

    - name: Configurar nodos masters secundarios
      ansible.builtin.raw: |
        cat <<EOF > /etc/systemd/system/k3s.service
        [Unit]
        Description=Lightweight Kubernetes
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=notify
        ExecStartPre=-/sbin/modprobe br_netfilter
        ExecStartPre=-/sbin/modprobe overlay
        ExecStart=/opt/bin/k3s server \
          --server https://{{ vip_ip }}:6443 \
          --token {{ k3s_token_output.stdout | trim }} \
          --tls-san {{ vip_ip }} \
          --node-name $(hostname -f) \
          --node-ip {{ ansible_host }}
        Restart=always
        KillMode=process
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity

        [Install]
        WantedBy=multi-user.target
        EOF
      when: inventory_hostname in groups['masters'] and inventory_hostname != k3s_master_ip

    - name: Iniciar K3s en todos los masters secundarios
      ansible.builtin.raw: |
        systemctl daemon-reload
        systemctl enable k3s
        systemctl start k3s
      when: inventory_hostname in groups['masters'] and inventory_hostname != k3s_master_ip

    - name: Esperar que K3s esté activo (masters secundarios)
      ansible.builtin.raw: |
        timeout=120
        while ! systemctl is-active k3s >/dev/null 2>&1 && [ $timeout -gt 0 ]; do
          echo "Esperando a que K3s esté activo... ($timeout s restantes)"
          sleep 5
          timeout=$((timeout-5))
        done
        systemctl is-active k3s || (journalctl -xeu k3s --no-pager -n 100 && exit 1)
      when: inventory_hostname in groups['masters'] and inventory_hostname != k3s_master_ip

    - name: Configurar nodos longhorn/workers
      ansible.builtin.raw: |
        cat <<EOF > /etc/systemd/system/k3s-agent.service
        [Unit]
        Description=Lightweight Kubernetes Node
        After=network-online.target

        [Service]
        Type=exec
        ExecStart=/opt/bin/k3s agent \
          --server https://{{ vip_ip }}:6443 \
          --token {{ k3s_token_output.stdout | trim }} \
          --node-ip {{ ansible_host }}
        Restart=always
        LimitNOFILE=1048576
        LimitNPROC=1048576
        LimitCORE=infinity

        [Install]
        WantedBy=multi-user.target
        EOF
      when: inventory_hostname in groups['longhorn_nodes']

    - name: Iniciar K3s-agent en nodos longhorn/workers
      ansible.builtin.raw: |
        systemctl daemon-reload
        systemctl enable k3s-agent
        systemctl start k3s-agent
      when: inventory_hostname in groups['longhorn_nodes']

    - name: Esperar que k3s-agent esté activo
      ansible.builtin.raw: |
        timeout=120
        while ! systemctl is-active k3s-agent >/dev/null 2>&1 && [ $timeout -gt 0 ]; do
          echo "Esperando K3s-agent (estado actual: $(systemctl show -p SubState --value k3s-agent))"
          sleep 5
          timeout=$((timeout-5))
        done
        systemctl is-active k3s-agent || (journalctl -xeu k3s-agent --no-pager -n 100 && exit 1)
      when: inventory_hostname in groups['longhorn_nodes']

    - name: Configurar kubeconfig en todos los nodos relevantes
      ansible.builtin.raw: |
        if [ -f /etc/rancher/k3s/k3s.yaml ]; then
          mkdir -p /home/core/.kube && \
          cp /etc/rancher/k3s/k3s.yaml /home/core/.kube/config && \
          sed -i 's/127.0.0.1/{{ vip_ip }}/g' /home/core/.kube/config && \
          chown core:core /home/core/.kube/config && \
          chmod 644 /home/core/.kube/config
        fi
      when: inventory_hostname in groups['masters'] or inventory_hostname in groups['longhorn_nodes']