---
- name: Configurar Virtual IP (VIP) para el Clúster
  hosts: masters
  become: true
  gather_facts: no  # Deshabilitar recolección de hechos para evitar dependencia de Python en Flatcar

  vars:
    vip: "10.17.5.10"
    interface: "eth0"  # Asegúrate de que este es el nombre de la interfaz en los nodos

  tasks:
    - name: Asegurar que Keepalived está instalado
      raw: |
        if ! which keepalived; then
          curl -LO https://www.keepalived.org/software/keepalived-2.0.19.tar.gz  # Actualiza la URL aquí si es necesario
          tar -xvzf keepalived-2.0.19.tar.gz
          cd keepalived-2.0.19
          sudo cp keepalived /usr/local/bin
        fi

    - name: Configurar la IP VIP en la red (solo en el primer nodo)
      raw: |
        ip addr add {{ vip }}/24 dev {{ interface }}
        ip link set dev {{ interface }} up
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Verificar conectividad del VIP
      raw: |
        ping -c 4 {{ vip }}
      register: ping_result
      failed_when: ping_result.rc != 0
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Configurar Keepalived para gestionar el VIP
      raw: |
        echo 'vrrp_instance VI_1 {
          state MASTER
          interface {{ interface }}
          virtual_router_id 51
          priority 101
          advert_int 1
          virtual_ipaddress {
              {{ vip }}
          }
        }' > /etc/keepalived/keepalived.conf

    - name: Iniciar y habilitar Keepalived
      raw: |
        systemctl start keepalived
        systemctl enable keepalived
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Configurar el archivo kubeconfig para apuntar al VIP
      raw: |
        sed -i 's/127.0.0.1/{{ vip }}/g' /etc/rancher/k3s/k3s.yaml
      when: inventory_hostname in groups['masters']