- name: Configurar Virtual IP (VIP) para el Clúster
  hosts: masters
  become: true
  gather_facts: no  # Deshabilitar recolección de hechos para evitar dependencia de Python en Flatcar

  vars:
    vip: "10.17.5.10"
    interface: "eth0"  # Asegúrate de que este es el nombre de la interfaz en los nodos

  tasks:
    - name: Asegurar que el paquete 'keepalived' esté instalado (para RedHat)
      ansible.builtin.raw: |
        if ! rpm -q keepalived; then
          sudo yum install -y keepalived
        fi
      when: ansible_facts['os_family'] == "RedHat"

    - name: Asegurar que el paquete 'keepalived' esté instalado (para Debian/Ubuntu)
      ansible.builtin.raw: |
        if ! dpkg -l | grep -q keepalived; then
          sudo apt-get install -y keepalived
        fi
      when: ansible_facts['os_family'] == "Debian"

    - name: Configurar la IP VIP en la red (solo en el primer nodo)
      ansible.builtin.shell: |
        ip addr add {{ vip }}/24 dev {{ interface }}
        ip link set dev {{ interface }} up
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Verificar conectividad del VIP
      ansible.builtin.command: ping -c 4 {{ vip }}
      register: ping_result
      failed_when: ping_result.rc != 0
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Configurar Keepalived para gestionar el VIP
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
              state MASTER
              interface {{ interface }}
              virtual_router_id 51
              priority 101
              advert_int 1
              virtual_ipaddress {
                  {{ vip }}
              }
          }
      notify:
        - Restart Keepalived
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Iniciar y habilitar Keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: started
        enabled: true
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Configurar el archivo kubeconfig para apuntar al VIP
      ansible.builtin.shell: |
        sed -i 's/127.0.0.1/{{ vip }}/g' /etc/rancher/k3s/k3s.yaml
      when: inventory_hostname in groups['masters']

  handlers:
    - name: Restart Keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: restarted