- name: Configurar Virtual IP (VIP) para el Clúster
  hosts: masters
  become: true
  gather_facts: yes
  vars:
    vip: "10.17.5.10"
    interface: "eth0"  # Asegúrate de que este es el nombre de la interfaz en los nodos

  tasks:
    - name: Asegurar que el paquete 'keepalived' esté instalado
      ansible.builtin.yum:
        name: keepalived
        state: present
      when: ansible_os_family == "RedHat"

    - name: Asegurar que el paquete 'keepalived' esté instalado en Debian/Ubuntu
      ansible.builtin.apt:
        name: keepalived
        state: present
      when: ansible_os_family == "Debian"

    - name: Configurar la IP VIP en la red
      ansible.builtin.shell: |
        ip addr add {{ vip }}/24 dev {{ interface }}
        ip link set dev {{ interface }} up
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Verificar conectividad del VIP
      ansible.builtin.command: ping -c 4 {{ vip }}
      register: ping_result
      failed_when: ping_result.rc != 0
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Configurar HAProxy o un servicio similar para gestionar el tráfico al VIP
      ansible.builtin.copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              log /dev/log local0
              log /dev/log local1 notice
              chroot /usr/share/haproxy
              stats socket /var/run/haproxy.sock mode 660 level admin
              maxconn 200

          defaults
              log     global
              option  httplog
              option  dontlognull
              timeout connect 5000ms
              timeout client  50000ms
              timeout server  50000ms

          frontend http_front
              bind *:80
              default_backend http_back

          backend http_back
              server master1 10.17.4.21:80 check
              server master2 10.17.4.22:80 check
              server master3 10.17.4.23:80 check

      notify:
        - Restart HAProxy
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Configurar Keepalived para gestionar el VIP
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
              state MASTER
              interface {{ interface }}
              virtual_router_id 51
              priority 101
              advert_int 1
              virtual_ipaddress {
                  {{ vip }}
              }
          }
      notify:
        - Restart Keepalived
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Iniciar y habilitar Keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: started
        enabled: true
      when: inventory_hostname == 'master1.cefaslocalserver.com'

    - name: Reiniciar HAProxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
      when: inventory_hostname == 'master1.cefaslocalserver.com'

  handlers:
    - name: Restart HAProxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted

    - name: Restart Keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: restarted