- name: Reemplazar endpoint API por IP VIP en nodos master
  hosts: masters
  become: true
  gather_facts: yes
  vars:
    api_vip: "https://10.17.5.10:6443"

  tasks:
    - name: Hacer copia de seguridad de k3s.yaml si existe
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /etc/rancher/k3s/k3s.yaml.bak
        remote_src: yes
        backup: yes
      ignore_errors: true

    - name: Verificar si existe el archivo k3s.yaml
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: k3s_yaml_status

    - name: Reemplazar IP del API server en k3s.yaml
      ansible.builtin.lineinfile:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: '^server:.*'
        line: "server: {{ api_vip }}"
      when: k3s_yaml_status.stat.exists

    - name: Reiniciar k3s en nodos master
      ansible.builtin.systemd:
        name: k3s
        state: restarted
      when: k3s_yaml_status.stat.exists