- name: Reemplazar endpoint API por IP VIP en nodos master
  hosts: masters:workers
  become: true
  vars:
    api_vip: "https://10.17.5.10:6443"
  tasks:
    - name: Hacer copia de seguridad de config.yaml si existe
      raw: |
        if [ -f /etc/rancher/k3s/config.yaml ]; then cp /etc/rancher/k3s/config.yaml /etc/rancher/k3s/config.yaml.bak; fi
      ignore_errors: true

    - name: Reemplazar IP del API server en config.yaml
      raw: |
        sed -i 's|^server:.*|server: {{ api_vip }}|' /etc/rancher/k3s/config.yaml

    - name: Reiniciar k3s o k3s-agent
      raw: |
        if systemctl status k3s &>/dev/null; then
          systemctl restart k3s
        elif systemctl status k3s-agent &>/dev/null; then
          systemctl restart k3s-agent
        fi