- name: Reemplazar endpoint API por IP VIP
  hosts: masters:workers
  become: true
  vars:
    api_vip: "https://10.17.5.10:6443"
  tasks:
    - name: Hacer copia de seguridad de config.yaml si existe
      ansible.builtin.copy:
        src: /etc/rancher/k3s/config.yaml
        dest: /etc/rancher/k3s/config.yaml.bak
        remote_src: true
      ignore_errors: true

    - name: Reemplazar IP del API server en config.yaml
      ansible.builtin.lineinfile:
        path: /etc/rancher/k3s/config.yaml
        regexp: '^server:.*'
        line: "server: {{ api_vip }}"
        backup: true
      when: ansible_facts['os_family'] == 'Flatcar'

    - name: Reiniciar k3s o k3s-agent
      ansible.builtin.shell: |
        if systemctl status k3s &>/dev/null; then
          systemctl restart k3s
        elif systemctl status k3s-agent &>/dev/null; then
          systemctl restart k3s-agent
        fi
      args:
        executable: /bin/bash
